discord:
  token: ""
  
telegram:
  bot_token: ""
  chat_id: ""
  allowed_user_ids: []

monitoring:
  tracked_users: []
  
  timezone: "Asia/Tehran"
  
  voice_monitoring_duration: 10  # 10s
  
  dm_check_duration: 10  # 10s

github_actions:
  run_interval: 5
