discord:
  token: ""
  
telegram:
  bot_token: ""
  chat_id: ""
  allowed_user_ids: []

monitoring:
  tracked_users: [992943668161953873, 1198400306338336821, 956212484283453551]
  
  timezone: "Asia/Tehran"
  
  voice_monitoring_duration: 30  # 30s
  
  dm_check_duration: 30  # 30s

github_actions:
  run_interval: 5
